Vagrant.configure(2) do | config |
   config.vm.define  "ansible_controlnode" do | acn |
        acn.vm.box = "ubuntu/jammy64"
        acn.vm.network "private_network", ip: "192.168.10.10", virtualbox_intnet: "ansible_cluster"
        acn.vm.provider "virtualbox" do | cnsvb |
            cnsvb.name="ansible_controlnode"
            cnsvb.cpus=1
            cnsvb.memory=1024
        end      
        acn.vm.provision "shell", path: "provisioners/sh/setupcontrolnode.sh"
    end
    (1..2).each do | index |
        config.vm.define "ansible_managednode_#{index}" do | node |
            node.vm.box = "ubuntu/jammy64"
            node.vm.network "private_network", ip: "192.168.10.#{index+10}", virtualbox_intnet: "ansible_cluster"
            node.vm.provider "virtualbox" do | nodevb |
                nodevb.name="ansible_managednode_#{index}"
            end
            node.vm.provision "shell", path: "provisioners/sh/setupmanagednode.sh"   
        end
    end        
end